var express = require('express');
var http = require('http');
var app = express();
var port = process.env.PORT || 8080;
var appRoutes = require('./routes/appRoutes');
var mongoose = require('mongoose');
var bodyParser = require('body-parser');
var cors=require('cors');
mongoose.connect('mongodb://him12:him123@ds163650.mlab.com:63650/digiangulardb');
app.use(cors());
app.use(bodyParser.urlencoded({extended: true}));
app.use(bodyParser.json());
app.use('/', appRoutes);
http.createServer(app).listen(port);
console.log("BackEnd Server Is On ", port);
